from __future__ import annotations

from enum import Enum


class ErrorCode(Enum):
    PROTOCOL_ERROR = "PROTOCOL_ERROR"
    AUTH_FAILED = "AUTH_FAILED"
    TOO_MANY_CONNECTIONS = "TOO_MANY_CONNECTIONS"
    BAD_ROLE = "BAD_ROLE"
    BAD_SESSION = "BAD_SESSION"
    SESSION_TAKEN = "SESSION_TAKEN"
    BAD_NAME = "BAD_NAME"
    BAD_LABEL = "BAD_LABEL"
    NAME_TAKEN = "NAME_TAKEN"
    UNKNOWN_OP = "UNKNOWN_OP"
    BAD_TEXT = "BAD_TEXT"
    BAD_CUSTOM_TYPE = "BAD_CUSTOM_TYPE"
    TEXT_TOO_LARGE = "TEXT_TOO_LARGE"
    CUSTOM_PAYLOAD_TOO_LARGE = "CUSTOM_PAYLOAD_TOO_LARGE"
    UNKNOWN_TARGET = "UNKNOWN_TARGET"
    AMBIGUOUS_TARGET = "AMBIGUOUS_TARGET"


ERROR_CODE_VALUES: tuple[str, ...] = tuple(code.value for code in ErrorCode)
